[package]
name = "sophia"
version = "0.1.0"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]
description = "A Rust toolkit for RDF and Linked Data"
repository = "https://github.com/pchampin/sophia_rs"
documentation = "https://docs.rs/sophia"
keywords = ["rdf", "linked-data", "semantic-web"]

[dependencies]
error-chain = "0.12.0"
language-tag = "0.9.0"
lazy_static = "1.1.0"
pest = "2.0.2"
pest_derive = "2.0.1"
regex = "1.0.5"
resiter = "0.2.0"
url = "1.7.1"
weak-table = "0.2.3"
