[package]
name = "sophia"
version = "0.1.0"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]

[dependencies]
language-tag = "0.9.0"
lazy_static = "1.0.1"
pest = "1.0.6"
pest_derive = "1.0.7"
regex = "1.0.0"
resiter = { git = "https://github.com/matthiasbeyer/resiter" }
url = "1.7.0"
weak-table = "0.2.3"
