[package]
name = "sophia"
version = "0.2.1"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]
description = "A Rust toolkit for RDF and Linked Data"
repository = "https://github.com/pchampin/sophia_rs"
documentation = "https://docs.rs/sophia"
readme = "../README.md"
license = "CECILL-C"
keywords = ["rdf", "linked-data", "semantic-web"]

edition = "2018"


[dependencies]
coercible_errors = "0.1.3"
error-chain = "0.12.0"
language-tag = "0.9.0"
lazy_static = "1.2.0"
pest = "2.1.0"
pest_derive = "2.1.0"
quick-xml = "0.14.0"
regex = "1.1.0"
rental = "0.5.2"
resiter = "0.3.0"
url = "1.7.2"
weak-table = "0.2.3"
