[package]
name = "sophia"
version = "0.1.0"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]

[dependencies]
language-tag = "0.9.0"
lazy_static = "1.1.0"
pest = "1.0.6"
pest_derive = "1.0.8"
regex = "1.0.5"
resiter = "0.2.0"
url = "1.7.1"
weak-table = "0.2.3"
