[package]
name = "sophia"
version = "0.4.0"
authors = ["Pierre-Antoine Champin <pchampin@liris.cnrs.fr>"]
description = "A Rust toolkit for RDF and Linked Data"
repository = "https://github.com/pchampin/sophia_rs"
documentation = "https://docs.rs/sophia"
readme = "../README.md"
license = "CECILL-C"
keywords = ["rdf", "linked-data", "semantic-web"]
edition = "2018"

[package.metadata.docs.rs]
all-features = true

[features]
default = []
xml = ["quick-xml", "percent-encoding"]

[dependencies]
language-tag = "0.9.0"
lazy_static = "1.4.0"
regex = "1.3.4"
resiter = "0.4.0"
rio_api = { version = "0.4.0", features = ["generalized"] }
rio_turtle = { version = "0.4.0", features = ["generalized"] }
url = "2.1.1"
weak-table = "0.2.3"
thiserror = "1.0.11"

quick-xml = { version = "0.17.2", optional = true }
percent-encoding = { version = "2.1.0", optional = true }
